// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;

namespace FitnessStudio.Models;

public partial class KalendKund : ObservableObject
{
    [ObservableProperty] public int kalendKundID;

    [ObservableProperty] public int? extKalendID;

    [ObservableProperty] public int? extKundID;

    public virtual Kalender ExtKalend { get; set; }

    public virtual Kunden ExtKund { get; set; }
}