// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;

namespace FitnessStudio.Models;

public partial class Kalender : ObservableObject
{
    [ObservableProperty] public int kalendID;

    [ObservableProperty] public DateTime kalendDatum;

    [ObservableProperty] public TimeSpan kalendZeit;

    [ObservableProperty] public int kalendTrainID;

    [ObservableProperty] public string kalendAktivName;

    public virtual ICollection<KalendKund> KalendKund { get; set; } = new List<KalendKund>();

    public virtual Trainer KalendTrain { get; set; }
}