// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;

namespace FitnessStudio.Models;

public partial class Karte : ObservableObject
{
    [ObservableProperty] public int karteID;

    [ObservableProperty] public string karteName;

    [ObservableProperty] public double kartePrice;

    [ObservableProperty] public int karteWert;

    public virtual ICollection<Kunden> Kunden { get; set; } = new List<Kunden>();
}