// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CommunityToolkit.Mvvm.ComponentModel;

namespace FitnessStudio.Models;

public partial class Kunden : ObservableObject
{
    [ObservableProperty] public int kundID;

    [ObservableProperty] public DateTime kundGebDatum;

    [ObservableProperty] public string kundVorname;

    [ObservableProperty] public string kundNachname;

    [ObservableProperty] public string kundAdresse;

    [ObservableProperty] public int kundPLZ;

    [ObservableProperty] public int? kundKartNum;

    [ObservableProperty] public bool kundConsent;

    [ObservableProperty] public int? kundKartGuthaben;

    public virtual ICollection<KalendKund> KalendKund { get; set; } = new List<KalendKund>();

    public virtual Karte KundKartNumNavigation { get; set; }

    public virtual Postleitzahlen KundPLZNavigation { get; set; }

    public virtual ICollection<Rechnung> Rechnung { get; set; } = new List<Rechnung>();
}