// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;

namespace FitnessStudio.Models;

public partial class Postleitzahlen : ObservableObject
{
    [ObservableProperty] public int postID;

    [ObservableProperty] public string postOrt;

    public virtual ICollection<Kunden> Kunden { get; set; } = new List<Kunden>();

    public virtual ICollection<Trainer> Trainer { get; set; } = new List<Trainer>();
}