// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;

namespace FitnessStudio.Models;

public partial class Rechnung : ObservableObject
{
    [ObservableProperty] public int rechID;

    [ObservableProperty] public DateTime rechDatum;

    [ObservableProperty] public int rechKundID;

    [ObservableProperty] public double rechSumme;

    [ObservableProperty] public bool rechIstBezahlt;

    public virtual Kunden RechKund { get; set; }
}