// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CommunityToolkit.Mvvm.ComponentModel;

namespace FitnessStudio.Models;

public partial class Trainer : ObservableObject
{
    [ObservableProperty] public int trainID;

    [ObservableProperty] public DateTime trainGebDatum;

    [ObservableProperty] public string trainVorname;

    [ObservableProperty] public string trainNachname;

    [ObservableProperty] public string trainAdresse;

    [ObservableProperty] public int trainPLZ;

    [ObservableProperty] public bool yoga;

    [ObservableProperty] public bool stepAerobic;

    [ObservableProperty] public bool tanzAerobic;

    [ObservableProperty] public bool pilates;

    [ObservableProperty] public bool sprungfitness;

    [ObservableProperty] public bool stretching;

    [ObservableProperty] public bool fitball;

    [ObservableProperty] public bool koerperSkulptur;

    [ObservableProperty] public bool crossfit;

    public virtual ICollection<Kalender> Kalender { get; set; } = new List<Kalender>();

    public virtual Postleitzahlen TrainPLZNavigation { get; set; }
}